### ISSUE TITLE
Init in a folder name containing hyphens causes quirky naming

### ISSUE THREAD

**Issue by robinjac** [reaptor/elmish-land#13]
Hyphens should be removed. In general we should make sure the naming of modules behaves nicely.

Example using `Testing-Elmish-Land` leads to this:

![image](https://github.com/reaptor/elmish-land/assets/9025089/1a4ae94c-cded-43ba-8612-ce375349d630)

**Comment by klofberg** [comment]
How do you propose this should work? I feel it's confusing to rename the folder.
