### ISSUE TITLE
Server command not working if .fsproj file has a different name then the project folder

### ISSUE THREAD

**Issue by robinjac** [reaptor/elmish-land#14]
The project folder name should be independent of running `dotnet elmish-land server` command.

![image](https://github.com/reaptor/elmish-land/assets/9025089/bf1402cc-ec30-4280-bc47-c73d418b2d15)

**Comment by klofberg** [comment]
This is intentional and by convention. Maybe a better error message is appropriate. An alternative is that we don't allow multiple project files in the folder but I think it's better to require the same name for the project file and folder.

**Comment by klofberg** [comment]
I will add a settings i elmish-land.json to specify the project file.
